In [49]:
import re
import csv
import urllib.parse

def process_file(file_path):
    """
    Processes a text file containing team member information and converts it to a CSV file.

    Args:
        file_path (str): The path to the text file.

    Returns:
        None
    """

    with open(file_path, 'r', encoding='utf-8') as file, open(file_path.replace('.txt', '.csv'), 'w', newline='', encoding='utf-8') as csvfile:
        reader = file.readlines()
        writer = csv.writer(csvfile)

        # Write header row
        writer.writerow(['User ID', 'Name', 'Title', 'Location', 'Role'])

        # strip all elements in the reader list
        reader = list(map(lambda x: x.strip(), reader))

        # remove all elements from the reader list that are empty
        reader = list(filter(lambda x: x != '', reader))

        # Process data in groups of 5 lines, handling potential errors
        for i in range(0, len(reader), 5):
            try:
                # Extract data from each group
                url = reader[i].strip()
                name = '"' + reader[i + 1].strip() + '"'
                title = '"' + reader[i + 2].strip() + '"'
                location = '"' + reader[i + 3].strip() + '"'
                role = '"' + reader[i + 4].strip() + '"'

                # Parse the URL to extract the user ID and org ID
                parsed_url = urllib.parse.urlparse(url)
                org_id = parsed_url.path.split(':orgid:')[1].split('/')[0]  # Extract org ID from path

                # Write data to CSV
                writer.writerow([org_id, name, title, location, role])

            except Exception as e:
                print(f"Error processing row starting at line {i}: {e}")
                print(f"Row content: {reader[i:i+5]}")

# Example usage:
file_path = 'team_members.txt'  # Replace with the actual file path
process_file(file_path)

In [50]:
# load teams_members.csv as pandas
import pandas as pd
df = pd.read_csv(file_path.replace('.txt', '.csv'))
df

,User ID,Name,Title,Location,Role
0,0c457a00-bef2-4129-9b71-de3e80f4a8ab,"""Nelson, Rhodri B""","""Senior Teaching Fellow in Computational Data ...","""RSM 4.96, 4th Floor, Royal School of Mines, S...","""Owner"""
1,81b935fd-f918-4831-8485-1ea5f4e6bb9a,"""Beg, Marijan""","""Teaching Fellow in Computational Data Science""","""4.95, 4th Floor, Royal School of Mines, South...","""Owner"""
2,909ae2b1-26e7-4622-adc8-c309689d3922,"""Salah, Parastoo""","""Teaching Fellow Position in Geo-Energy with D...","""4th Floor, Royal School of Mines, South Kensi...","""Owner"""
3,91f4918a-b495-4583-968e-38b3b6c01d88,"""Percival, James R""","""Senior Teaching Fellow""","""4.94, 4th Floor, Royal School of Mines, South...","""Owner"""
4,9dc0c754-c4a1-466f-9d8e-1361fe8f9cb7,"""van Schalkwyk, Francois""","""Senior Research Software Engineer""","""355, 3rd Floor, Royal School of Mines, South ...","""Owner"""
...,...,...,...,...,...
237,fc6fe779-6464-401c-bef4-c18705dc3d01,"""Godinot, Mayeul W""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
238,fdde3e15-eb47-4ea6-8386-ff2b687adadd,"""LENG, Peiyi""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
239,fde8b4c9-e65a-46ec-89aa-9fc83a8d710a,"""Yin, Yu""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
240,fdea234d-33cd-4435-b582-f9d25765cfa8,"""Fung, Hadrian""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
241,ff299846-0834-433f-84f8-d2c3b18b430a,"""Guler, Defne""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""

In [51]:
df

,User ID,Name,Title,Location,Role
0,0c457a00-bef2-4129-9b71-de3e80f4a8ab,"""Nelson, Rhodri B""","""Senior Teaching Fellow in Computational Data ...","""RSM 4.96, 4th Floor, Royal School of Mines, S...","""Owner"""
1,81b935fd-f918-4831-8485-1ea5f4e6bb9a,"""Beg, Marijan""","""Teaching Fellow in Computational Data Science""","""4.95, 4th Floor, Royal School of Mines, South...","""Owner"""
2,909ae2b1-26e7-4622-adc8-c309689d3922,"""Salah, Parastoo""","""Teaching Fellow Position in Geo-Energy with D...","""4th Floor, Royal School of Mines, South Kensi...","""Owner"""
3,91f4918a-b495-4583-968e-38b3b6c01d88,"""Percival, James R""","""Senior Teaching Fellow""","""4.94, 4th Floor, Royal School of Mines, South...","""Owner"""
4,9dc0c754-c4a1-466f-9d8e-1361fe8f9cb7,"""van Schalkwyk, Francois""","""Senior Research Software Engineer""","""355, 3rd Floor, Royal School of Mines, South ...","""Owner"""
...,...,...,...,...,...
237,fc6fe779-6464-401c-bef4-c18705dc3d01,"""Godinot, Mayeul W""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
238,fdde3e15-eb47-4ea6-8386-ff2b687adadd,"""LENG, Peiyi""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
239,fde8b4c9-e65a-46ec-89aa-9fc83a8d710a,"""Yin, Yu""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
240,fdea234d-33cd-4435-b582-f9d25765cfa8,"""Fung, Hadrian""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""
241,ff299846-0834-433f-84f8-d2c3b18b430a,"""Guler, Defne""","""Taught Postgraduate""","""Royal School of Mines, South Kensington Campus""","""Member"""